server:
  applicationConnectors:
    - type: http
      port: 8000

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: username
  password: pa$$word
  url: jdbc:mysql://localhost:3306/challenge?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  properties:
    useSSL: false
